### ISSUE TITLE
Load a bit more content so it's clear there is more without having to start scrolling

### ISSUE THREAD

**Issue by thomasmaas** [Kuadrant/kuadrant.github.io#22]
<img width="1552" alt="Screenshot 2023-07-04 at 12 53 15" src="https://github.com/Kuadrant/kuadrant.github.io/assets/54224/5bd0725a-3971-4d31-9379-b3bc247fee81">

**Comment by jasonmadigan** [comment]
Agree - see https://github.com/Kuadrant/kuadrant.github.io/issues/22 (loads the features area without scrolling, so it's obvious there's more stuff on the page).
