### ISSUE TITLE
Getting Started link doesn´t work

### ISSUE THREAD

**Issue by pwright** [Kuadrant/kuadrant.github.io#34]
Starting at https://kuadrant.io/, clicking `Getting Started` gives me a 404.

The target is https://docs.kuadrant.io/multicluster-gateway-controller/docs/getting-started

It isn´t clear whether this should resolve to 

* https://docs.kuadrant.io/getting-started/
* https://docs.kuadrant.io/multicluster-gateway-controller/docs/how-to/multicluster-gateways-walkthrough/
* https://docs.kuadrant.io/multicluster-gateway-controller/

IMO, that last link stands out as being the only of the docs that gives user an appreciation of what is going on.

**Comment by jasonmadigan** [comment]
Fixed via https://github.com/Kuadrant/kuadrant.github.io/pull/35 - but you have raised a good point in that dropping them into getting running may not be ideal. The overview (docs.kuadrant.io) may be a better getting started point.
